apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox-demo
  name: busybox-demo
  namespace: venkat
spec:
  containers:
  - image: busybox
    name: busybox-demo
    command:
    - /bin/sh
    - -c
    - sleep 3600
  tolerations:
  - key: "env"
    operator: "Equal"
    value: "dev"
    effect: "NoSchedule"
#  nodeSelector:
#    env: dev
