---
  - name: Playbook
    hosts: webservers
    become: yes
    become_user: root
    tasks:
    - name: Add the user 'sai' with a specific uid and a primary group of 'admin'
      ansible.builtin.user:
        name: sai
        comment: sai krishna
        shell: /bin/bash
        uid: 1004
        group: whell,sai