---
  - name: Playbook
    hosts: all
    become: yes
    become_user: root
    tasks:
    - name: Add the user 'Sai' with a specific uid and a primary group of 'admin'
      ansible.builtin.user:
        name: Sai
        comment: Sai Kodali
        shell: /bin/bash
        uid: 1004
        group: root