---
- name: Install Git
  hosts: all
  gather_facts: false
  become: true
  vars:
    version: 2.19.1
    prefix: /usr/local
    temp_dir: /tmp
    binary_dir: "{{ temp_dir }}/git-{{ version }}"
    url: "https://www.kernel.org/pub/software/scm/git/git-{{ version }}.tar.gz"
  tasks:
    - name: Install yum package
      yum:
        name:
          - curl-devel
          - expat-devel
          - gettext-devel
          - openssl-devel
          - zlib-devel
          - wget
          - gcc
          - cpan
"playbook-git-install.yml" 53L, 1161C

