- name: Ansible Copy Example Local to Remote
  hosts: "{{ target_hosts }}"
  tasks:
    - name: copying file with playbook
      become: true 
      copy:
        src: /root/ansible-to-copy.txt
        dest: /opt
        owner: venkat
        group: venkat        
        mode: 0644
